#!/usr/bin/env dash
fnCheckout () {
    for name in "$@"; do
        git rev-parse --verify $name >/dev/null 2>/dev/null && git checkout $name && exit
    done
}

name=$(basename $0)
if [ "$name" = "gitxMain" ]
then
    fnCheckout "main" "master" "mainline" "default"
elif [ "$name" = "gitxDev" ]
then
    fnCheckout "dev" "develop" "devel" "development"
fi