#!/bin/dash
doMerge () {
    for name in "$@"; do
        git rev-parse --verify $name >/dev/null 2>/dev/null && git merge $name && exit
    done
}

name=$(basename $0)
if [ "$name" = "x-git-mg-main" ]
then
    doMerge "main" "master" "mainline" "default"
elif [ "$name" = "x-git-mg-dev" ]
then
    doMerge "dev" "develop" "devel" "development"
fi